application:
  aws:
    sns:
      coj-signed: ${local.sns-prefix}:tis-trainee-details-coj-signed
      contact-details-provided: ${local.sns-prefix}:tis-trainee-details-contact-provided
      gmc-details-provided: ${local.sns-prefix}:tis-trainee-details-gmc-provided
    sqs:
      event: ${local.sqs-prefix}/
      basic-details-update: ${local.sqs-prefix}/tis-trainee-details-local-basic-details-update
      contact-details-update: ${local.sqs-prefix}/tis-trainee-details-local-contact-details-update
      gdc-details-update: ${local.sqs-prefix}/tis-trainee-details-local-gdc-details-update
      gmc-details-update: ${local.sqs-prefix}/tis-trainee-details-local-gmc-details-update
      personal-info-update: ${local.sqs-prefix}/tis-trainee-details-local-personal-info-update
      person-owner-update: ${local.sqs-prefix}/tis-trainee-details-local-person-owner-update
      profile-move: ${local.sqs-prefix}/tis-trainee-details-local-profile-move
  environment: local
  signature:
    secret-key: ${SIGNATURE_SECRET_KEY:not-very-secret-plain-text-value}

local:
  account-id: "000000000000"
  region: eu-west-2
  sns-prefix: arn:aws:sns:${local.region}:${local.account-id}
  sqs-prefix: ${spring.cloud.aws.endpoint}/${local.account-id}


spring:
  cloud:
    aws:
      credentials:
        access-key: ${local.account-id}
        secret-key: ${local.account-id}
      endpoint: http://${LOCALSTACK_HOST:localhost}:4566
      region:
        static: ${local.region}
