application:
  aws:
    sns:
      coj-signed: dummy
      contact-details-provided: dummy
      gmc-details-provided: dummy
    sqs:
      event: dummy
      basic-details-update: dummy
      contact-details-update: dummy
      gdc-details-update: dummy
      gmc-details-update: dummy
      personal-info-update: dummy
      person-owner-update: dummy
      profile-move: dummy

mongock:
  enabled: false

spring:
  cloud:
    aws:
      region:
        static: eu-west-2
      sqs:
        enabled: false
